image: golang:alpine


variables:
  REPO_NAME: github.com/goyak/yak

stages:
  - lint
  - build
  - test

before_script:
  - go version
  - echo $CI_BUILD_REF
  - echo $CI_PROJECT_DIR
  - mkdir -p $GOPATH/src/$REPO_NAME
  - rm -rf $GOPATH/src/$REPO_NAME
  - ln -s $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - apk add --no-cache git
  - ln -s /builds /go/src/gitlab.com
  - go get -u github.com/kardianos/govendor
  - cd $GOPATH/src/$REPO_NAME


lint-my-project:
  stage: lint
  script:
    - govendor fmt +local
    - git diff > /tmp/gitdiff
    - cat /tmp/gitdiff
    - test ! -s /tmp/gitdiff

build-my-project:
  stage: build
  script:
    - govendor sync
    - govendor build +local
  only:
    - master

test-my-project:
  stage: test
  script:
    - govendor sync
    - govendor test +local
